version: '3.8'

services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    container_name: changedetection
    hostname: changedetection
    volumes:
      - changedetection-data:/datastore # Persists your website data and settings
    ports:
      - "5000:5000" # Or your preferred host port
    environment:
      # Connects to the Playwright browser service defined below
      - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000/?stealth=1&--disable-web-security=true
      # Optional: Set a base URL if you are accessing changedetection.io via a reverse proxy
      # - BASE_URL=https://yourdomain.com/changedetection
      # Optional: Set timezone
      # - TZ=America/New_York
    restart: unless-stopped
    depends_on:
      - playwright-chrome

  playwright-chrome:
    image: browserless/chrome:latest # A popular image that includes Chrome and Playwright support
    container_name: playwright-chrome
    hostname: playwright-chrome
    # Optional: You might not need to expose ports externally if only changedetection needs access
    # ports:
    #   - "3000:3000"
    environment:
      # You can add browserless.io specific environment variables here if needed
      # For example, to increase connection timeout or enable stealth mode by default.
      # However, many options are passed via the PLAYWRIGHT_DRIVER_URL.
      - CONNECTION_TIMEOUT=300000 # Example: 5 minutes in milliseconds
      # Enable STEALTH mode if not passed in PLAYWRIGHT_DRIVER_URL
      # - STEALTH=true
      # Disable web security if not passed in PLAYWRIGHT_DRIVER_URL (use with caution)
      # - DEFAULT_DISABLE_WEB_SECURITY=true
    restart: unless-stopped

volumes:
  changedetection-data: # Defines the named volume for persistent storage
