services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO # to recognize nvme
      - SYS_ADMIN
    ports:
      - 18080:8080 # webapp
      - 18086:8086 # influxdb admin
    volumes:
      - /opt/scrutiny/config:/opt/scrutiny/config
      - /opt/scrutiny/influxdb2:/opt/scrutiny/influxdb
      - /run/udev:/run/udev
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd
      # - /dev/nvme0
