import = [
  "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless" # works on macOS only

opacity = 0.95
blur = true # works on macOS only

[font]
# normal.family = "MesloLGS Nerd Font Mono"
size = 11
