services:
  couchdb-obsidian-livesync:
    image: docker.io/oleduc/docker-obsidian-livesync-couchdb:master
    container_name: couchdb-obsidian-livesync
    restart: always
    env_file:
      - .env
    ports:
      - 5984:5984
    volumes:
      - /opt/couchdb/data:/opt/couchdb/data
