services:
  # deluge:
  #   image: lscr.io/linuxserver/deluge:latest
  #   container_name: deluge
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Sao_Paulo
  #     - DELUGE_LOGLEVEL=error #optional
  #   volumes:
  #     - /opt/deluge/config:/config
  #     # - /opt/docker/deluge-torrents:/data/torrents
  #     # - /mnt/nfs/torrents:/data/torrents
  #     - /opt/docker/test:/data/torrents
  #     # - /media/WDElements/data/torrents:/data/torrents
  #   ports:
  #     - 8112:8112
  #     - 6881:6881
  #     - 6881:6881/udp
  #     - 58846:58846 #optional
  #   restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Americas/Sao_Paulo
      - WEBUI_PORT=8180
      # - TORRENTING_PORT=30090
    volumes:
      - /opt/qbittorrent/appdata:/config
      # - /mnt/nfs/torrents:/downloads #optional
      - /mnt/nfs/torrents:/data/torrents #optional
    ports:
      - 8180:8180
      # - 6881:6881
      # - 6881:6881/udp
      - 30090:30090
      - 30090:30090/udp
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/radarr:/config
      - /mnt/nfs/videos:/data #optional
      # - /media/WDElements/data:/data #optional
      # - /opt/docker/deluge-torrents:/data/torrents
      - /mnt/nfs/torrents:/data/torrents
      # - /media/nvme/torrents/:/data/torrents
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/sonarr:/config:rw
      - /mnt/nfs/videos:/data #optional
      # - /media/WDElements/data:/data #optional
      # - /opt/docker/deluge-torrents:/data/torrents
      - /mnt/nfs/torrents/:/data/torrents
      # - /media/nvme/torrents/:/data/torrents
    ports:
      - 8989:8989
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/lidarr:/config:rw
      - /mnt/nfs/music:/music #optional
      # - /media/WDElements/data/:/data #optional
      # - /path/to/downloadclient-downloads:/downloads #optional
      # - /opt/docker/deluge-torrents:/data/torrents
      - /mnt/nfs/torrents/:/downloads
      # - /tmp/lidarr_test_torrents:/data/torrents
      # - /media/nvme/torrents/:/data/torrents
    ports:
      - 8686:8686
    restart: unless-stopped

  # readarr:
  #   image: lscr.io/linuxserver/readarr:develop
  #   container_name: readarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Sao_Paulo
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /opt/readarr:/config:rw
  #     - /media/nvme/books/:/data #optional
  #     - /media/WDElements/data/torrents/completed/:/downloads #optional
  #   ports:
  #     - 8787:8787
  #   restart: unless-stopped

  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - /opt/tautulli:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    ports:
      - 8181:8181

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/prowlarr:/config:rw
    ports:
      - 9696:9696 
    restart: unless-stopped

  # flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    # image: ghcr.io/flaresolverr/flaresolverr:latest
    # container_name: flaresolverr
    # environment:
    #   - LOG_LEVEL=${LOG_LEVEL:-info}
    #   - LOG_HTML=${LOG_HTML:-false}
    #   - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    #   - TZ=America/Sao_Paulo
    # ports:
    #   # - "${PORT:-8191}:8191"
    #   - 8191:8191
    # restart: unless-stopped
