
[ env ]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5

decorations = "Buttonless"
opacity=0.7
blur=true

[font]
normal.family = "JetBrainsMono NF"
# normal.family = "MesloLGS NF"
# normal.family = "Inconsolata"

#regular
size = 15 

#for video
# size = 35.0

[selection]
save_to_clipboard=true
# save_to_clipboard=false

[cursor]
style = {shape = "Underline", blinking= "Off"}

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
    # "~/.config/alacritty/themes/themes/github_light.toml"
]
