import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"
opacity=0.9
blur=true

[font]
normal.family = "JetBrainsMono NF"
# normal.family = "MesloLGS NF"
# normal.family = "Inconsolata"

#regular
size = 16 

#for video
# size = 35.0

[selection]
save_to_clipboard=true

[cursor]
style = {shape = "Underline", blinking= "Off"}
