exec-once = foot --server

bind = ALT, TAB, exec, $HOME/.config/hypr/scripts/alttab/enable.sh 'down'
bind = ALT SHIFT, TAB, exec, $HOME/.config/hypr/scripts/alttab/enable.sh 'up'

submap=alttab
bind = ALT, tab, sendshortcut, , tab, class:alttab
bind = ALT SHIFT, tab, sendshortcut, shift, tab, class:alttab
bind = ALT, dead_grave, sendshortcut, shift, tab, class:alttab

# accept on Ctrl release
bindrt = ALT, ALT_L, exec, $XDG_CONFIG_HOME/hypr/scripts/alttab/disable.sh ; hyprctl -q dispatch sendshortcut , return, class:alttab
bindrt = ALT, ALT_R, exec, $XDG_CONFIG_HOME/hypr/scripts/alttab/disable.sh ; hyprctl -q dispatch sendshortcut , return, class:alttab
bind = ALT, Return, exec, $XDG_CONFIG_HOME/hypr/scripts/alttab/disable.sh ; hyprctl -q dispatch sendshortcut , return, class:alttab
bind = ALT SHIFT, Return, exec, $XDG_CONFIG_HOME/hypr/scripts/alttab/disable.sh ; hyprctl -q dispatch sendshortcut , return, class:alttab
bind = ALT, escape, exec, $XDG_CONFIG_HOME/hypr/scripts/alttab/disable.sh ; hyprctl -q dispatch sendshortcut , escape,class:alttab
bind = ALT SHIFT, escape, exec, $XDG_CONFIG_HOME/hypr/scripts/alttab/disable.sh ; hyprctl -q dispatch sendshortcut , escape,class:alttab
submap = reset

# Alt-Tab picker window rules
windowrule = float,       class:alttab
windowrule = size 700 800, class:alttab
windowrule = center,      class:alttab
windowrule = noanim,      class:alttab
windowrule = bordersize 0,class:alttab
windowrule = stayfocused, class:alttab

windowrule = rounding 13, class:alttab

# Force full opacity (avoid fade difference)
# windowrule = opacity 1.0 override 1.0 override, class:alttab

# Disable shadows/glow
windowrule = noshadow, class:alttab

# Disable blur
# windowrule = noblur, class:alttab
