exec-once = uwsm app -- hypridle
exec-once = uwsm app -- waybar
exec-once = uwsm app -- hyprpaper
exec-once = uwsm app -- swayosd-server
exec-once = uwsm app -- libinput-gestures-setup start
exec-once = systemctl --user start hyprpolkitagent.service
exec-once = hyprpm reload -nn
exec-once = uwsm app -- waypaper --random
exec-once = keyd-application-mapper -d
exec-once = albert & disown


# Set visual profile (more fancy / less fancy) depending on battery/charging status
exec-once = ~/.config/hypr/scripts/visual-profile.sh --auto
