source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/plugins.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/windows.conf
source = ~/.config/hypr/alttab.conf

################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=eDP-1,preferred,auto,1.33
# monitor=HDMI-A-1,preferred,0x0,1.0
# monitor=eDP-1,3024x1890@60,0x0,1.5
# monitor=HDMI-A-1,2560x1440@60,0x0,1.0

# Disable internal when lid closes
bindl = , switch:on:Apple SMC power/lid events, exec, hyprctl keyword monitor "eDP-1,disable"

# Re-enable internal when lid opens (preferred mode, auto position, scale 1 — tweak as you like)
bindl = , switch:off:Apple SMC power/lid events, exec, sh -c 'sleep 0.2; hyprctl keyword monitor "eDP-1,preferred,auto,1.33"'

############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

# Cursor size
env = HYPRCURSOR_THEME,bibata-modern-classic
# env = HYPRCURSOR_THEME,catppuccin-macchiato-dark-cursors
env = HYPRCURSOR_SIZE,24
env = XCURSOR_SIZE,24

# Force all apps to use Wayland
env = GDK_BACKEND,wayland,x11
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_STYLE_OVERRIDE,kvantum
env = SDL_VIDEODRIVER,wayland
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
# env = OZONE_PLATFORM,wayland
env = XDG_SESSION_TYPE,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = GTK_USE_PORTAL,1

xwayland {
  force_zero_scaling = true
  use_nearest_neighbor = true
}

# Use XCompose file
env = XCOMPOSEFILE,~/.XCompose

# Don't show update on first launch
ecosystem {
  no_update_news = true
}
