# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant = intl
    kb_model = apple
    # kb_options = caps:super
    kb_options = caps:hyper
    kb_rules =

    follow_mouse = 0

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
        clickfinger_behavior = true
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    # workspace_swipe = true
    workspace_swipe_distance = 300 #default
    workspace_swipe_cancel_ratio = 0.3 
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

device {
    name = apple-spi-trackpad
    disable_while_typing = true
    sensitivity = 0.1
}
