# hyperkey-mode:capslock pressed

# Modifiers:
# C - Control++
# M - Meta/Super++
# A - Alt++h
# S - Shift++
# G - AltGr

# -----------
[alacritty]
# implement nav-mode
# space = overload(nav-mode, space)

# -----------
[firefox]
# universal sidebar toggle
hyperkey-mode.s = C-A-z

# implement nav-mode
# space = overload(nav-mode, space)

# -----------
[brave-browser]
# universal sidebar toggle
hyperkey-mode.s = C-A-s

# implement nav-mode
# space = overload(nav-mode, space)

# -----------
[chromium]
# implement nav-mode
# space = overload(nav-mode, space)

# -----------
[zen]
# universal sidebar toggle
hyperkey-mode.s = C-s

# implement nav-mode
# space = overload(nav-mode, space)

# -----------
[code]
# universal sidebar toggle
hyperkey-mode.s = C-b

# universal command palette
hyperkey-mode.space = C-S-p

# -----------
[obsidian]
# universal sidebar toggle
hyperkey-mode.s = S-A-s

# universal command palette
hyperkey-mode.space = C-p

# -----------
[1password]
# universal sidebar toggle
hyperkey-mode.s = C-S-d
web

# -----------
[tradingview]
# universal command palette
hyperkey-mode.space = C-k

# -----------
# Todoist
[chrome-*dlgohinmglaoopaiplliaecdpmnepmga*]
# universal sidebar toggle
hyperkey-mode.s = m

# universal command palette
hyperkey-mode.space = C-k

# -----------
# ChatGPT webapp
[chrome-*cadlkienfkclaiaibeoongdcgmdikeeg*]
# universal sidebar toggle
hyperkey-mode.s = C-S-s

# implement nav-mode
# space = overload(nav-mode, space)

# -----------
# Gemini webapp
[chrome-*caidcmannjgahlnbpmidmiecjcoiiigg*]
# implement nav-mode
# space = overload(nav-mode, space)
