
# NOTE: The panic sequence *<backspace>+<escape>+<enter>* will force keyd to terminate.

# https://www.karimarttila.fi/keyboard/2023/11/16/linux-keyboard-configuration-with-keyd.html

### NOTE:
# This file needs to be in:
# /etc/keyd/default.conf

### HELP SECTION BEGIN ###

# Web site: https://github.com/rvaiya/keyd

##### KEYD #################
# When you edit /etc/keyd/default.conf file:
# cd /etc/keyd
# cn # Open VSCode
# In another terminal:
# sudo journalctl -eu keyd -f
# ... this way you immediately see if there is some error,
# when you load new configuration (after saving the file):
# sudo keyd reload
# Finally when you are ready, in the /etc/keyd: add changes to git.

# Find keys with tool:
# sudo keyd monitor

# List keys that you can use with keyd:
# sudo keyd list-keys

# Modifiers:
# C - Control++
# M - Meta/Super++
# A - Alt++h
# S - Shift++
# G - AltGr

### HELP SECTION END ###

# =================== KEYBOARD IDENTIFICATIONS ========================================
# NOTE: Later on if you find out that some configuration does not work on Dygma vs Laptop keyboard,
# you can use separate ids sections.
[ids]
*

# ========================= GLOBAL OPTIONS ========================================

[global]
# The time (in milliseconds) separating the initial execution of a macro
# sequence and the first repetition (default=600)
macro_timeout = 600

# The time separating successive executions of a macro (default: 50)
macro_repeat_timeout = 500

# If set, this will turn the capslock light on whenever a layer is active.
# Note: Some wayland compositors will aggressively toggle LED state rendering this option unusable.
layer_indicator=1
#
#If set, this will add a timeout (*in microseconds*) between each emitted key in a macro sequence. This is
# useful to avoid overflowing the input buffer on some systems.
macro_sequence_timeout = 500

#The maximum time between successive keys interpreted as part of a chord (default: 50)
chord_timeout = 50

# The length of time a chord must be held before being activated. (default: 0)
chord_hold_timeout = 0

# If non-zero, timeout a oneshot layer activation after the supplied number of milliseconds.
# (default: 0)
oneshot_timeout = 0

# By default, keyd will inject additional control keypresses where necessary in order to prevent programs from
# seeing additional modifier taps (E.g alt in firefox). If set, this option disables that behaviour.
# (default: 0)
disable_modifier_guard = 0

# If non-zero, ignore the tap behaviour of an overloaded key if it is held for the given number of miliseconds.
# (default: 0).
overload_tap_timeout = 300
# overload_tap_timeout = 0


# ============================ MAIN ========================================
[main]
# Hyperkey mode: activates hyperkey-mode layer (-> (control+meta+alt+shift) if there are no keybind found in ~/.config/key/apps.conf), or esc if alone
capslock = overload(hyperkey-mode, esc)

# Meta keys switched to Ctrl + tap-to-toggle in Hyprland (Meta-Tab)
leftmeta = overload(control, M-tab)
rightmeta = overload(control, M-tab)

# Left Ctrl switched to Super/Meta + tap-to-toggle in web browser (Ctrl-Tab)
leftcontrol = overload(meta, C-tab)

# Right Alt switched to Super/Meta
rightalt = rightmeta

# Nav Layer
# space = overload(nav, space)


[hyperkey-mode:C-M-A-S]


[nav-mode]
h = left
j = down
k = up
l = right

m = pageup
n = pagedown

S-k = pageup
S-j = pagedown

u = home
o = end
b = backspace
w = delete
