version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: "ntfy://osteiner:jyx*EMQ6zna_vgc4hmp@ntfy.sh/XxGPCCMxbAF9p3VAEzmq"
      WATCHTOWER_MONITOR_ONLY: true
      # WATCHTOWER_RUN_ONCE: true
